version: '3.8'

services:
  # 1. Database: PostgreSQL
  postgres-db:
    image: postgres:15
    container_name: cric-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cricbuzz_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Cache: Redis
  redis-cache:
    image: redis:7-alpine
    container_name: cric-redis
    ports:
      - "6379:6379"

  # 3. Message Broker: Zookeeper (Kafka's Manager)
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: cric-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

# 4. Message Broker: Kafka (Stable Zookeeper Version)
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: cric-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT


volumes:
  postgres_data: