version: '3.8'

services:
  # 1. Database: PostgreSQL
  postgres-db:
    image: postgres:15
    container_name: cric-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cricbuzz_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Cache: Redis
  redis-cache:
    image: redis:7-alpine
    container_name: cric-redis
    ports:
      - "6379:6379"

  # 3. Zookeeper
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: cric-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # 4. Kafka
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: cric-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # 5. Ingestion Service
  ingestion-service:
    build: ./ingestion-service
    container_name: cric-ingestion
    depends_on:
      - kafka
      - redis-cache
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_DATA_REDIS_HOST=redis-cache
      - SPRING_DATA_REDIS_PORT=6379
    deploy:
      resources:
        limits:
          memory: 300M

  # 6. Processor Service
  processor-service:
    build: ./processor-service
    container_name: cric-processor
    depends_on:
      - kafka
      - postgres-db
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/cricbuzz_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    deploy:
      resources:
        limits:
          memory: 300M

  #FrontEnd 

cric-frontend:
    build: ./cric-frontend-deploy
    container_name: cric-frontend
    ports:
      - "80:80"
    depends_on:
      - ingestion-service
      - processor-service
    deploy:
      resources:
        limits:
          memory: 100M
volumes:
  postgres_data:
